version: "3.8"
services:
    # my-app:
    #   image: #gcp image here
    #   ports:
    #     - 3001:3001
    mongodb:
      image: mongo
      ports:
      - 27017:27017
      environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=toor
    mongo-express:
      image: mongo-express
      restart: always
      ports:
      - 8080:8081
      environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=toor
      - ME_CONFIG_MONGODB_SERVER=mongodb
      depends_on:
      - "mongodb"
