version: "3.8"
services:
    my-app:
      image: gcr.io/ivory-amplifier-375607/my-app@sha256:c590b377fea7ded93f11b36f114c7c019465c5f7b7f87a972eb9e7600bdf513c
      ports:
        - 3000:300
    mongodb:
      image: mongo
      ports:
      - 27017:27017
      environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=toor
    mongo-express:
      image: mongo-express
      restart: always
      ports:
      - 8080:8081
      environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=toor
      - ME_CONFIG_MONGODB_SERVER=mongodb
      depends_on:
      - "mongodb"
